language: r
cache: packages
dist: trusty

r_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

matrix:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
