language: r
cache: packages
os: linux
dist: xenial

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change
